export const locales = ['en', 'ar', 'tr'] as const;
export type Locale = (typeof locales)[number];
export const isLocale = (value: string): value is Locale => locales.includes(value as Locale);

export type SiteCopy = {
  skip: string; nav: string[]; search: string; closeSearch: string; openMenu: string; closeMenu: string; searchPlaceholder: string; noResults: string; contact: string;
  heroKicker: string; heroTitle: string; heroText: string; heroImageAlt: string; interiorImageAlt: string; explore: string; since: string; stats: [string, string][];
  aboutKicker: string; aboutTitle: string; aboutText: string; fields: [string, string][];
  projectsKicker: string; projectsTitle: string; viewProject: string;
  projects: { slug: string; name: string; tag: string; description: string; facts: string[]; image: string; gallery: string[] }[];
  projectsPageKicker: string; projectsPageTitle: string; projectsPageIntro: string; projectsPageMetaTitle: string; projectsPageMetaDescription: string;
  backToProjects: string; projectFactsLabel: string; projectGalleryLabel: string; projectCtaTitle: string; projectCtaText: string;
  amenityKicker: string; amenityTitle: string; amenities: string[];
  investKicker: string; investTitle: string; investText: string; investPoints: string[];
  ctaTitle: string; ctaText: string; form: string[]; send: string; footer: string;
  formMessage: string; formRequired: string; formInvalidEmail: string; formSending: string;
  formSuccessTitle: string; formSuccessText: string; formErrorText: string; formSendAnother: string; formPhoneCode: string;
  contactPageKicker: string; contactPageTitle: string; contactPageIntro: string; contactPageMetaTitle: string; contactPageMetaDescription: string;
  contactLocationLabel: string; contactLocationValue: string; contactPhoneLabel: string; contactWhatsappLabel: string; contactEmailLabel: string; contactHoursLabel: string; contactHoursValue: string; contactMapTitle: string;
  whatsappMessage: string; floatingWhatsappLabel: string; floatingCallLabel: string;
  formFieldRequired: string; formRequiredNote: string; countryPriorityLabel: string; countryAllLabel: string;
};

export const copy: Record<Locale, SiteCopy> = {
  en: {
    skip: 'Skip to content', nav: ['Home', 'About', 'Projects', 'Why Türkiye', 'Contact'], search: 'Search', closeSearch: 'Close search', openMenu: 'Open menu', closeMenu: 'Close menu', searchPlaceholder: 'Search projects, amenities, or services…', noResults: 'No matching results found.', contact: 'Talk to our team',
    heroKicker: 'Luxury real estate developer · Istanbul', heroTitle: 'Live beautifully.\nInvest wisely.', heroText: 'Distinctive homes and considered communities, created in Istanbul for modern life and long-term value.', heroImageAlt: 'Istanbul skyline and Bosphorus waterfront at sunset', interiorImageAlt: 'Contemporary luxury residential interior in Istanbul', explore: 'Explore our projects', since: 'Building with purpose since 2014', stats: [['2014', 'Founded in Istanbul'], ['3', 'Signature developments'], ['3', 'Regional partnerships']],
    aboutKicker: 'Who we are', aboutTitle: 'Spaces designed for the way life should feel.', aboutText: 'HADARA is an Istanbul-based developer of luxury villas and high-quality residential projects. Since 2014, we have combined elegant design, sustainable construction, and premium living environments for families and investors, supported by trusted partnerships across Qatar, Kuwait, and Saudi Arabia.', fields: [['01', 'Architectural services'], ['02', 'Residential project development'], ['03', 'Building materials export']],
    projectsKicker: 'Selected developments', projectsTitle: 'A considered approach to place.', viewProject: 'View project', projects: [
      { slug: 'marmara-haven-villa', name: 'Marmara Haven Villa', tag: 'Private villa · Marmara coast', description: 'A private seaside haven on a 637 m² plot, with open views, a private elevator, deep-water well, and full smart-home system.', facts: ['4 floors', '576 m²', '5 bedrooms', '7 bathrooms'], image: 'https://static.wixstatic.com/media/3510f9_c4e14f77b98144a59013aca49d0e7c40~mv2.jpeg', gallery: ['https://static.wixstatic.com/media/3510f9_edf7cfb26e7a4752840d32259dd1193b~mv2.jpeg', 'https://static.wixstatic.com/media/3510f9_2d5451e74ab542aa80af9e029255fbb2~mv2.jpeg', 'https://static.wixstatic.com/media/3510f9_56cbe047aa0f46068a060cec785911b9~mv2.jpeg'] },
      { slug: 'lotus-yasam', name: 'Lotus Yaşam', tag: 'New residential project · Beylikdüzü, Istanbul', description: 'A 21,000 m² residential development in Beylikdüzü shaped around modern living, comprehensive social amenities, flexible installments, and delivery at the end of 2028.', facts: ['21,000 m² land', 'Social amenities', 'Flexible payment', 'Delivery 2028'], image: 'https://static.wixstatic.com/media/3510f9_6e8795e3581c4582a0a197a6ab6dd4cd~mv2.jpg', gallery: ['https://static.wixstatic.com/media/3510f9_0199bf18496c4cce99e0d36a80748221~mv2.jpg', 'https://static.wixstatic.com/media/3510f9_b4e011b7cd844b0dbc19b420bee212d6~mv2.jpg', 'https://static.wixstatic.com/media/3510f9_ed4c8345dcf5464e9f42a4a993df784a~mv2.jpg'] },
      { slug: 'lotus-koru', name: 'Lotus Koru', tag: 'Residential project · Beylikdüzü, Istanbul', description: 'A delivered residential development in Beylikdüzü, built around comfortable modern apartments and shared green spaces.', facts: ['Beylikdüzü, Istanbul', 'Modern apartments', 'Delivered project'], image: 'https://static.wixstatic.com/media/3510f9_ad7dc0dc93a74625a1542c2cad01ebcd~mv2.jpeg', gallery: ['https://static.wixstatic.com/media/3510f9_5da11f8697ff4b1cbb8ac3763d35bce1~mv2.jpeg', 'https://static.wixstatic.com/media/3510f9_8548ec6a543f440fa11f989b7ee37748~mv2.jpeg', 'https://static.wixstatic.com/media/3510f9_af156a90b5d44ce29d99a67e19be43c1~mv2.jpeg'] },
    ],
    projectsPageKicker: 'Our developments', projectsPageTitle: 'Every HADARA project, in one place.', projectsPageIntro: 'From a private villa on the Marmara coast to residential communities in Beylikdüzü, explore the developments shaping HADARA’s portfolio in Istanbul.',
    projectsPageMetaTitle: 'Projects | HADARA Real Estate', projectsPageMetaDescription: 'Browse HADARA Real Estate’s villas and residential developments in Istanbul, including Marmara Haven Villa, Lotus Yaşam, and Lotus Koru in Beylikdüzü.',
    backToProjects: 'Back to all projects', projectFactsLabel: 'At a glance', projectGalleryLabel: 'Gallery', projectCtaTitle: 'Interested in this project?', projectCtaText: 'Speak with a HADARA advisor about availability, pricing, and viewings.',
    amenityKicker: 'Elevated living', amenityTitle: 'Everyday comfort, thoughtfully included.', amenities: ['Residents club', 'Private fitness center', 'Concierge services', 'Valet parking', 'Co-working spaces', 'Rooftop & infinity pool', 'Smart-home integration'],
    investKicker: 'Live & invest in Türkiye', investTitle: 'A home with a wider horizon.', investText: 'Our team supports international buyers through the property journey, from choosing the right home to understanding residence and citizenship pathways linked to qualified real estate investment.', investPoints: ['Property residence guidance', 'Turkish citizenship pathways', 'Local market expertise'],
    ctaTitle: 'Begin your Istanbul property journey.', ctaText: 'Tell us what you are looking for. A HADARA advisor will contact you shortly.', form: ['First name', 'Last name', 'Email address', 'Phone number'], send: 'Request a consultation', footer: 'Luxury real estate development in Istanbul, Türkiye.',
    formMessage: 'Your message', formRequired: 'Please fill in all required fields.', formInvalidEmail: 'Please enter a valid email address.', formSending: 'Sending…',
    formSuccessTitle: 'Thank you for reaching out.', formSuccessText: 'We truly appreciate your interest in HADARA. Your message has been received, and one of our advisors will personally contact you shortly to assist you.', formErrorText: 'Something went wrong while sending your message. Please try again in a moment.', formSendAnother: 'Send another message', formPhoneCode: 'Country code',
    contactPageKicker: 'Get in touch', contactPageTitle: 'We would love to hear from you.', contactPageIntro: 'Whether you are exploring a new home or considering an investment, our team in Istanbul is ready to guide you through every step.',
    contactPageMetaTitle: 'Contact HADARA Real Estate | Istanbul', contactPageMetaDescription: 'Get in touch with HADARA Real Estate in Beylikdüzü, Istanbul. Call, message us on WhatsApp, or send an inquiry about our luxury villas and residential projects.',
    contactLocationLabel: 'Location', contactLocationValue: 'Beylikdüzü, Istanbul, Türkiye', contactPhoneLabel: 'Phone', contactWhatsappLabel: 'WhatsApp', contactEmailLabel: 'Email', contactHoursLabel: 'Working hours', contactHoursValue: 'Monday – Saturday, 9:00 AM – 6:00 PM (closed Sundays)', contactMapTitle: 'Map showing HADARA in Beylikdüzü, Istanbul',
    whatsappMessage: 'Hello, I would like to inquire about HADARA Real Estate projects.', floatingWhatsappLabel: 'Chat with us on WhatsApp', floatingCallLabel: 'Call HADARA Real Estate',
    formFieldRequired: 'Required', formRequiredNote: '* Required field', countryPriorityLabel: 'Popular', countryAllLabel: 'All countries',
  },
  ar: {
    skip: 'انتقل إلى المحتوى', nav: ['الرئيسية', 'من نحن', 'المشاريع', 'لماذا تركيا', 'تواصل معنا'], search: 'بحث', closeSearch: 'إغلاق البحث', openMenu: 'فتح القائمة', closeMenu: 'إغلاق القائمة', searchPlaceholder: 'ابحث عن مشروع أو خدمة أو ميزة…', noResults: 'لا توجد نتائج مطابقة.', contact: 'تحدث مع فريقنا',
    heroKicker: 'تطوير عقاري فاخر · إسطنبول', heroTitle: 'عِش بجمال.\nواستثمر بحكمة.', heroText: 'منازل استثنائية ومجتمعات مدروسة نصنعها في إسطنبول للحياة العصرية والقيمة طويلة الأمد.', heroImageAlt: 'أفق إسطنبول ومضيق البوسفور وقت الغروب', interiorImageAlt: 'تصميم داخلي فاخر لشقة سكنية عصرية في إسطنبول', explore: 'استكشف مشاريعنا', since: 'نبني بهدف منذ عام 2014', stats: [['2014', 'تأسست في إسطنبول'], ['3', 'مشاريع مميزة'], ['3', 'شراكات إقليمية']],
    aboutKicker: 'من نحن', aboutTitle: 'مساحات مصممة لتمنح الحياة شعورها الحقيقي.', aboutText: 'حضارة مطوّر عقاري مقره إسطنبول، متخصص في الفلل الفاخرة والمشاريع السكنية عالية الجودة. منذ عام 2014، نجمع بين التصميم الأنيق والبناء المستدام وبيئات العيش الراقية للعائلات والمستثمرين.', fields: [['01', 'الخدمات المعمارية'], ['02', 'تطوير المشاريع السكنية'], ['03', 'تصدير مواد البناء']],
    projectsKicker: 'مشاريع مختارة', projectsTitle: 'رؤية مدروسة للمكان.', viewProject: 'عرض المشروع', projects: [
      { slug: 'marmara-haven-villa', name: 'فيلا Marmara Haven', tag: 'فيلا خاصة · ساحل مرمرة', description: 'ملاذ خاص على البحر فوق أرض بمساحة 637 م²، بإطلالات مفتوحة ومصعد خاص وبئر مياه عميق ونظام منزل ذكي متكامل.', facts: ['4 طوابق', '576 م²', '5 غرف نوم', '7 حمامات'], image: 'https://static.wixstatic.com/media/3510f9_c4e14f77b98144a59013aca49d0e7c40~mv2.jpeg', gallery: ['https://static.wixstatic.com/media/3510f9_edf7cfb26e7a4752840d32259dd1193b~mv2.jpeg', 'https://static.wixstatic.com/media/3510f9_2d5451e74ab542aa80af9e029255fbb2~mv2.jpeg', 'https://static.wixstatic.com/media/3510f9_56cbe047aa0f46068a060cec785911b9~mv2.jpeg'] },
      { slug: 'lotus-yasam', name: 'Lotus Yaşam', tag: 'مشروع سكني جديد · بيليكدوزو، إسطنبول', description: 'مشروع سكني على مساحة 21,000 م² في بيليكدوزو للحياة العصرية، بمرافق اجتماعية متكاملة وخطط دفع مرنة وتسليم نهاية 2028.', facts: ['أرض 21,000 م²', 'مرافق اجتماعية', 'دفع مرن', 'تسليم 2028'], image: 'https://static.wixstatic.com/media/3510f9_6e8795e3581c4582a0a197a6ab6dd4cd~mv2.jpg', gallery: ['https://static.wixstatic.com/media/3510f9_0199bf18496c4cce99e0d36a80748221~mv2.jpg', 'https://static.wixstatic.com/media/3510f9_b4e011b7cd844b0dbc19b420bee212d6~mv2.jpg', 'https://static.wixstatic.com/media/3510f9_ed4c8345dcf5464e9f42a4a993df784a~mv2.jpg'] },
      { slug: 'lotus-koru', name: 'Lotus Koru', tag: 'مشروع سكني · بيليكدوزو، إسطنبول', description: 'مشروع سكني مُسلَّم في بيليكدوزو، صُمم حول شقق عصرية مريحة ومساحات خضراء مشتركة.', facts: ['بيليكدوزو، إسطنبول', 'شقق عصرية', 'مشروع مُسلَّم'], image: 'https://static.wixstatic.com/media/3510f9_ad7dc0dc93a74625a1542c2cad01ebcd~mv2.jpeg', gallery: ['https://static.wixstatic.com/media/3510f9_5da11f8697ff4b1cbb8ac3763d35bce1~mv2.jpeg', 'https://static.wixstatic.com/media/3510f9_8548ec6a543f440fa11f989b7ee37748~mv2.jpeg', 'https://static.wixstatic.com/media/3510f9_af156a90b5d44ce29d99a67e19be43c1~mv2.jpeg'] },
    ],
    projectsPageKicker: 'مشاريعنا', projectsPageTitle: 'كل مشاريع حضارة في مكان واحد.', projectsPageIntro: 'من فيلا خاصة على ساحل مرمرة إلى مجتمعات سكنية في بيليكدوزو، استكشف المشاريع التي تشكّل محفظة حضارة في إسطنبول.',
    projectsPageMetaTitle: 'مشاريعنا | حضارة للتطوير العقاري', projectsPageMetaDescription: 'تعرّف على فلل ومشاريع حضارة السكنية في إسطنبول، بما فيها فيلا Marmara Haven، وLotus Yaşam، وLotus Koru في بيليكدوزو.',
    backToProjects: 'العودة إلى كل المشاريع', projectFactsLabel: 'نظرة سريعة', projectGalleryLabel: 'معرض الصور', projectCtaTitle: 'مهتم بهذا المشروع؟', projectCtaText: 'تحدث مع أحد مستشاري حضارة حول التوفر والأسعار ومواعيد المعاينة.',
    amenityKicker: 'حياة أرقى', amenityTitle: 'راحة يومية صُممت بعناية.', amenities: ['نادي السكان', 'مركز لياقة خاص', 'خدمات الكونسيرج', 'خدمة صف السيارات', 'مساحات عمل مشتركة', 'سطح ومسبح إنفينيتي', 'أنظمة المنزل الذكي'],
    investKicker: 'عِش واستثمر في تركيا', investTitle: 'منزل يفتح لك أفقًا أوسع.', investText: 'ندعم المشترين الدوليين في رحلتهم العقارية، من اختيار المنزل المناسب إلى فهم مسارات الإقامة والجنسية المرتبطة بالاستثمار العقاري المؤهل.', investPoints: ['إرشاد الإقامة العقارية', 'مسارات الجنسية التركية', 'خبرة بالسوق المحلي'],
    ctaTitle: 'ابدأ رحلتك العقارية في إسطنبول.', ctaText: 'أخبرنا عمّا تبحث عنه وسيتواصل معك مستشار من حضارة قريبًا.', form: ['الاسم الأول', 'اسم العائلة', 'البريد الإلكتروني', 'رقم الهاتف'], send: 'اطلب استشارة', footer: 'تطوير عقاري فاخر في إسطنبول، تركيا.',
    formMessage: 'رسالتك', formRequired: 'يرجى تعبئة جميع الحقول المطلوبة.', formInvalidEmail: 'يرجى إدخال بريد إلكتروني صحيح.', formSending: 'جارٍ الإرسال…',
    formSuccessTitle: 'شكرًا جزيلاً لتواصلك معنا.', formSuccessText: 'يسعدنا اهتمامك بحضارة للتطوير العقاري. تم استلام رسالتك بنجاح، وسيتواصل معك أحد مستشارينا شخصيًا في أقرب وقت ممكن لمساعدتك.', formErrorText: 'حدث خطأ أثناء إرسال رسالتك. يرجى المحاولة مرة أخرى بعد قليل.', formSendAnother: 'إرسال رسالة أخرى', formPhoneCode: 'مفتاح الدولة',
    contactPageKicker: 'تواصل معنا', contactPageTitle: 'يسعدنا تواصلك معنا.', contactPageIntro: 'سواء كنت تبحث عن منزل جديد أو تفكر باستثمار عقاري، فريقنا في إسطنبول جاهز لمرافقتك في كل خطوة.',
    contactPageMetaTitle: 'تواصل مع حضارة للتطوير العقاري | إسطنبول', contactPageMetaDescription: 'تواصل مع حضارة للتطوير العقاري في بيليكدوزو، إسطنبول. اتصل بنا، راسلنا عبر واتساب، أو أرسل استفسارك حول فللنا الفاخرة ومشاريعنا السكنية.',
    contactLocationLabel: 'الموقع', contactLocationValue: 'بيليكدوزو، إسطنبول، تركيا', contactPhoneLabel: 'الهاتف', contactWhatsappLabel: 'واتساب', contactEmailLabel: 'البريد الإلكتروني', contactHoursLabel: 'ساعات العمل', contactHoursValue: 'الإثنين – السبت، ٩ صباحًا – ٦ مساءً (عطلة يوم الأحد)', contactMapTitle: 'خريطة توضح موقع حضارة في بيليكدوزو، إسطنبول',
    whatsappMessage: 'مرحبًا، أرغب بالاستفسار عن مشاريع حضارة العقارية.', floatingWhatsappLabel: 'تواصل معنا عبر واتساب', floatingCallLabel: 'اتصل بحضارة العقارية',
    formFieldRequired: 'حقل مطلوب', formRequiredNote: '* حقل مطلوب', countryPriorityLabel: 'الأكثر طلبًا', countryAllLabel: 'كل الدول',
  },
  tr: {
    skip: 'İçeriğe geç', nav: ['Ana Sayfa', 'Hakkımızda', 'Projeler', 'Neden Türkiye', 'İletişim'], search: 'Ara', closeSearch: 'Aramayı kapat', openMenu: 'Menüyü aç', closeMenu: 'Menüyü kapat', searchPlaceholder: 'Proje, olanak veya hizmet arayın…', noResults: 'Eşleşen sonuç bulunamadı.', contact: 'Ekibimizle görüşün',
    heroKicker: 'Lüks gayrimenkul geliştiricisi · İstanbul', heroTitle: 'Güzel yaşayın.\nAkıllıca yatırım yapın.', heroText: 'İstanbul’da modern yaşam ve uzun vadeli değer için tasarlanan seçkin evler ve özenli yaşam alanları.', heroImageAlt: 'Gün batımında İstanbul silüeti ve Boğaz kıyısı', interiorImageAlt: 'İstanbul’da çağdaş lüks konut iç mekânı', explore: 'Projelerimizi keşfedin', since: '2014’ten beri amaçla inşa ediyoruz', stats: [['2014', 'İstanbul’da kuruldu'], ['3', 'Özel proje'], ['3', 'Bölgesel ortaklık']],
    aboutKicker: 'Biz kimiz', aboutTitle: 'Hayatın hissettirmesi gerektiği gibi tasarlanan mekânlar.', aboutText: 'HADARA, İstanbul merkezli lüks villa ve nitelikli konut projeleri geliştiricisidir. 2014’ten bu yana aileler ve yatırımcılar için zarif tasarım, sürdürülebilir yapı ve seçkin yaşam alanlarını bir araya getiriyoruz.', fields: [['01', 'Mimari hizmetler'], ['02', 'Konut projesi geliştirme'], ['03', 'Yapı malzemeleri ihracatı']],
    projectsKicker: 'Seçili projeler', projectsTitle: 'Mekâna özenli bir yaklaşım.', viewProject: 'Projeyi görüntüle', projects: [
      { slug: 'marmara-haven-villa', name: 'Marmara Haven Villa', tag: 'Özel villa · Marmara kıyısı', description: '637 m² arsa üzerinde açık manzaralar, özel asansör, derin su kuyusu ve tam akıllı ev sistemi sunan deniz kenarı villası.', facts: ['4 kat', '576 m²', '5 yatak odası', '7 banyo'], image: 'https://static.wixstatic.com/media/3510f9_c4e14f77b98144a59013aca49d0e7c40~mv2.jpeg', gallery: ['https://static.wixstatic.com/media/3510f9_edf7cfb26e7a4752840d32259dd1193b~mv2.jpeg', 'https://static.wixstatic.com/media/3510f9_2d5451e74ab542aa80af9e029255fbb2~mv2.jpeg', 'https://static.wixstatic.com/media/3510f9_56cbe047aa0f46068a060cec785911b9~mv2.jpeg'] },
      { slug: 'lotus-yasam', name: 'Lotus Yaşam', tag: 'Yeni konut projesi · Beylikdüzü, İstanbul', description: 'Beylikdüzü’de modern yaşam, kapsamlı sosyal olanaklar, esnek taksitler ve 2028 sonu teslim planıyla şekillenen 21.000 m² konut projesi.', facts: ['21.000 m² arsa', 'Sosyal olanaklar', 'Esnek ödeme', '2028 teslim'], image: 'https://static.wixstatic.com/media/3510f9_6e8795e3581c4582a0a197a6ab6dd4cd~mv2.jpg', gallery: ['https://static.wixstatic.com/media/3510f9_0199bf18496c4cce99e0d36a80748221~mv2.jpg', 'https://static.wixstatic.com/media/3510f9_b4e011b7cd844b0dbc19b420bee212d6~mv2.jpg', 'https://static.wixstatic.com/media/3510f9_ed4c8345dcf5464e9f42a4a993df784a~mv2.jpg'] },
      { slug: 'lotus-koru', name: 'Lotus Koru', tag: 'Konut projesi · Beylikdüzü, İstanbul', description: 'Beylikdüzü’de tamamlanmış ve teslim edilmiş, konforlu modern daireler ve ortak yeşil alanlar etrafında şekillenen bir konut projesi.', facts: ['Beylikdüzü, İstanbul', 'Modern daireler', 'Teslim edilmiş proje'], image: 'https://static.wixstatic.com/media/3510f9_ad7dc0dc93a74625a1542c2cad01ebcd~mv2.jpeg', gallery: ['https://static.wixstatic.com/media/3510f9_5da11f8697ff4b1cbb8ac3763d35bce1~mv2.jpeg', 'https://static.wixstatic.com/media/3510f9_8548ec6a543f440fa11f989b7ee37748~mv2.jpeg', 'https://static.wixstatic.com/media/3510f9_af156a90b5d44ce29d99a67e19be43c1~mv2.jpeg'] },
    ],
    projectsPageKicker: 'Projelerimiz', projectsPageTitle: 'Tüm HADARA projeleri tek yerde.', projectsPageIntro: 'Marmara kıyısındaki özel bir villadan Beylikdüzü’ndeki konut topluluklarına kadar, HADARA’nın İstanbul’daki projelerini keşfedin.',
    projectsPageMetaTitle: 'Projeler | HADARA Gayrimenkul', projectsPageMetaDescription: 'HADARA Gayrimenkul’ün İstanbul’daki villa ve konut projelerini keşfedin: Marmara Haven Villa, Lotus Yaşam ve Beylikdüzü’ndeki Lotus Koru.',
    backToProjects: 'Tüm projelere dön', projectFactsLabel: 'Öne çıkanlar', projectGalleryLabel: 'Galeri', projectCtaTitle: 'Bu projeyle ilgileniyor musunuz?', projectCtaText: 'Uygunluk, fiyatlandırma ve gezi randevuları için bir HADARA danışmanıyla görüşün.',
    amenityKicker: 'Seçkin yaşam', amenityTitle: 'Gündelik konfor, özenle düşünüldü.', amenities: ['Sakinler kulübü', 'Özel fitness merkezi', 'Concierge hizmetleri', 'Vale hizmeti', 'Ortak çalışma alanları', 'Çatı terası ve sonsuzluk havuzu', 'Akıllı ev entegrasyonu'],
    investKicker: 'Türkiye’de yaşayın ve yatırım yapın', investTitle: 'Daha geniş bir ufka açılan ev.', investText: 'Uluslararası alıcılara doğru evi seçmekten oturum ve vatandaşlık yollarını anlamaya kadar gayrimenkul yolculuğunda destek oluyoruz.', investPoints: ['Gayrimenkul oturum rehberliği', 'Türk vatandaşlığı yolları', 'Yerel pazar uzmanlığı'],
    ctaTitle: 'İstanbul’daki gayrimenkul yolculuğunuza başlayın.', ctaText: 'Aradığınız evi bize anlatın. HADARA danışmanı kısa süre içinde sizinle iletişime geçsin.', form: ['Ad', 'Soyad', 'E-posta adresi', 'Telefon numarası'], send: 'Danışmanlık talep edin', footer: 'İstanbul, Türkiye’de lüks gayrimenkul geliştirme.',
    formMessage: 'Mesajınız', formRequired: 'Lütfen tüm gerekli alanları doldurun.', formInvalidEmail: 'Lütfen geçerli bir e-posta adresi girin.', formSending: 'Gönderiliyor…',
    formSuccessTitle: 'Bize ulaştığınız için teşekkür ederiz.', formSuccessText: 'HADARA’ya gösterdiğiniz ilgi için minnettarız. Mesajınız alındı; danışmanlarımızdan biri size yardımcı olmak üzere kısa süre içinde şahsen sizinle iletişime geçecek.', formErrorText: 'Mesajınız gönderilirken bir sorun oluştu. Lütfen kısa bir süre sonra tekrar deneyin.', formSendAnother: 'Başka bir mesaj gönder', formPhoneCode: 'Ülke kodu',
    contactPageKicker: 'Bize ulaşın', contactPageTitle: 'Sizden haber almak isteriz.', contactPageIntro: 'İster yeni bir ev arıyor olun ister bir yatırımı değerlendiriyor olun, İstanbul’daki ekibimiz her adımda size rehberlik etmeye hazır.',
    contactPageMetaTitle: 'HADARA Gayrimenkul ile İletişime Geçin | İstanbul', contactPageMetaDescription: 'Beylikdüzü, İstanbul’daki HADARA Gayrimenkul ile iletişime geçin. Bizi arayın, WhatsApp’tan yazın veya lüks villa ve konut projelerimiz hakkında bilgi talep edin.',
    contactLocationLabel: 'Konum', contactLocationValue: 'Beylikdüzü, İstanbul, Türkiye', contactPhoneLabel: 'Telefon', contactWhatsappLabel: 'WhatsApp', contactEmailLabel: 'E-posta', contactHoursLabel: 'Çalışma saatleri', contactHoursValue: 'Pazartesi – Cumartesi, 09:00 – 18:00 (Pazar günleri kapalı)', contactMapTitle: 'Beylikdüzü, İstanbul’da HADARA’yı gösteren harita',
    whatsappMessage: 'Merhaba, HADARA Gayrimenkul projeleri hakkında bilgi almak istiyorum.', floatingWhatsappLabel: 'WhatsApp’tan bize yazın', floatingCallLabel: 'HADARA Gayrimenkul’ü arayın',
    formFieldRequired: 'Zorunlu alan', formRequiredNote: '* Zorunlu alan', countryPriorityLabel: 'Popüler', countryAllLabel: 'Tüm ülkeler',
  },
};
